import type { Contact } from "./types";

export const mockContacts: Contact[] = [
  {
    id: "1",
    name: "Alice Johnson",
    company: "TechCorp Inc.",
    email: "alice.johnson@techcorp.com",
    phone: "+1 (555) 123-4567",
    status: "active",
    lastActivity: new Date(2024, 0, 15),
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "2",
    name: "Bob Smith",
    company: "StartupXYZ",
    email: "bob.smith@startupxyz.com",
    phone: "+1 (555) 234-5678",
    status: "prospect",
    lastActivity: new Date(2024, 0, 12),
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "3",
    name: "Carol Davis",
    company: "Enterprise Solutions",
    email: "carol.davis@enterprise.com",
    phone: "+1 (555) 345-6789",
    status: "customer",
    lastActivity: new Date(2024, 0, 10),
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "4",
    name: "David Wilson",
    company: "Innovation Labs",
    email: "david.wilson@innovationlabs.com",
    phone: "+1 (555) 456-7890",
    status: "inactive",
    lastActivity: new Date(2023, 11, 28),
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "5",
    name: "Emma Thompson",
    company: "Digital Dynamics",
    email: "emma.thompson@digitaldynamics.com",
    phone: "+1 (555) 567-8901",
    status: "active",
    lastActivity: new Date(2024, 0, 14),
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "6",
    name: "Frank Miller",
    company: "CloudTech Systems",
    email: "frank.miller@cloudtech.com",
    phone: "+1 (555) 678-9012",
    status: "prospect",
    lastActivity: new Date(2024, 0, 8),
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "7",
    name: "Grace Lee",
    company: "DataFlow Corp",
    email: "grace.lee@dataflow.com",
    phone: "+1 (555) 789-0123",
    status: "customer",
    lastActivity: new Date(2024, 0, 13),
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "8",
    name: "Henry Brown",
    company: "NextGen Ventures",
    email: "henry.brown@nextgen.com",
    phone: "+1 (555) 890-1234",
    status: "active",
    lastActivity: new Date(2024, 0, 11),
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "9",
    name: "Ivy Chen",
    company: "AI Innovations",
    email: "ivy.chen@aiinnovations.com",
    phone: "+1 (555) 901-2345",
    status: "prospect",
    lastActivity: new Date(2024, 0, 9),
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "10",
    name: "Jack Rodriguez",
    company: "Mobile First",
    email: "jack.rodriguez@mobilefirst.com",
    phone: "+1 (555) 012-3456",
    status: "inactive",
    lastActivity: new Date(2023, 11, 25),
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "11",
    name: "Kate Anderson",
    company: "Growth Partners",
    email: "kate.anderson@growthpartners.com",
    phone: "+1 (555) 123-4567",
    status: "customer",
    lastActivity: new Date(2024, 0, 16),
    avatar: "/placeholder.svg?height=32&width=32",
  },
  {
    id: "12",
    name: "Liam O'Connor",
    company: "Security Solutions",
    email: "liam.oconnor@securitysolutions.com",
    phone: "+1 (555) 234-5678",
    status: "active",
    lastActivity: new Date(2024, 0, 7),
    avatar: "/placeholder.svg?height=32&width=32",
  },
];
